# -*- coding: utf-8 -*-
"""Play Store App Review Analysis Project.ipynb by harsh

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqKwBQtshoKecNEt_iLuJ2sCq5INfD4Q

# **Project Name**    -  **Play Store App Review Analysis**

##### **Project Type**    - EDA
##### **Contribution**    - Individual

# GitHub Link -

https://github.com/Harsh-10-harsh/playstore_app_review

# **Problem Statement**

**BUSINESS PROBLEM OVERVIEW**


The Google Play Store hosts millions of mobile applications spanning a wide range of categories and functionalities. With such a large volume of apps available, it becomes increasingly challenging for developers to understand user preferences and market dynamics, and for users to identify high-quality applications. This project aims to analyze the Google Play Store dataset to extract actionable insights regarding app performance, user engagement, and content quality. The goal is to uncover patterns that influence app ratings, user installs, and overall success, thereby helping developers and businesses make data-driven decisions for app development and marketing.

In the highly competitive mobile app market, app developers and businesses face key challenges, including:

**1. Understanding User Preferences:** What factors most influence user ratings and reviews? How do price, category, and app size affect user satisfaction?

**2. Market Positioning:** Which app categories are most popular or have the highest user engagement? Are there specific features or characteristics that top-performing apps share?

**3. Monetization Strategy:** Do free apps perform better than paid ones in terms of downloads and ratings? How does app pricing influence installs?

**4. Quality Control and Compliance:** How do content ratings (e.g., Everyone, Teen, Mature) and update frequency impact user perception and engagement?

By analyzing these questions, this project can support strategic planning in app development, marketing, and customer experience optimization. The results will be useful for app developers, product managers, and digital marketers aiming to improve their app's visibility, user base, and profitability on the Google Play Store.

#### **Define Your Business Objective?**

To analyze Google Play Store data to identify key factors influencing app success and provide actionable insights for improving app performance and user engagement.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.


5. You have to create at least 20 logical & meaningful charts having important insights.

[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Core Libraries
import pandas as pd  # for data manipulation
import numpy as np   # for numerical operations

# Visualization Libraries
import matplotlib.pyplot as plt  # for basic plotting
import seaborn as sns            # for advanced statistical visualizations
sns.set(style='whitegrid')       # set default style for seaborn

# Warnings and Display Settings
import warnings
warnings.filterwarnings('ignore')

# To install NumPy and Pandas
!pip install numpy pandas

"""### Dataset Loading"""

# establishing connection between drive and google colab , so we can see drive in colab
from google.colab import drive
drive.mount('/content/drive')

# Load Dataset
dataset = pd.read_csv('/content/drive/MyDrive/Play Store Data.csv')

"""### Dataset First View"""

# Dataset First
dataset.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns
dataset.shape

"""### Dataset Information"""

# Dataset Info
dataset.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
len(dataset[dataset.duplicated()])

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
print(dataset.isnull().sum())

# Visualizing the missing values
# Checking Null Value by plotting Heatmap
sns.heatmap(dataset.isnull(), cbar=False)

"""### What did you know about your dataset?

The dataset contains information about 10,841 Android applications listed on the Google Play Store and includes 13 different attributes for each app.

These attributes are: App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, and Android Ver. Most of the data columns are textual object type, while Rating is the only column with numeric float data.

Some columns have missing values, notably Rating with 1,474 missing entries, and a few others such as Type, Content Rating, Current Ver, and Android Ver also having a small number of missing values.

The Reviews, Size, Installs, and Price columns are stored as text and may require preprocessing for quantitative analysis.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
dataset.columns

# Dataset Describe
dataset.describe(include='all')

"""### Variables Description

**1. App**

*   Type: Text (string)
*   Description: The name of the application as listed on the Google Play Store.

**2. Category**

*   Type: Text (string)
*   Description: The category under which the app is listed (e.g., "ART_AND_DESIGN", "EDUCATION", "GAME").

**3. Rating**

*   Type: Float (numeric)
*   Description: The average user rating of the app (range 1.0 to 5.0). Some values may be missing.
Reviews

**4. Reviews**

*   Type: Text (should be numeric)
*   Description: The total number of user reviews submitted for the app. Stored as text and may need conversion to integer.

**5. Size**

*   Type: Text (string)
*   Description: The size of the app (e.g., “19M”, “14k”). Some entries are "Varies with device" and may require standardization.

**6. Installs**

*   Type: Text (string)
*   Description: The number of times the app has been installed. Values include symbols like “+” and commas (e.g., “1,000+”).

**7. Type**

*   Type: Text (string)
*   Description: Indicates whether the app is “Free” or “Paid”.

**8. Price**

*   Type: Text (string, monetary value)
*   Description: The cost of the app. For free apps, this is “0”; for paid apps, it includes a currency symbol (e.g., “$4.99”).

**9. Content Rating**

*   Type: Text (string)
*   Description: The age group the app is suitable for (e.g., “Everyone”, “Teen”, “Mature 17+”).

**10. Genres**

*   Type: Text (string)
*   Description: A more specific classification of the app. Some apps may have multiple genres (e.g., "Action;Adventure").

**11. Last Updated**

*   Type: Text (date string)
*   Description: The last date the app was updated, in formats like “January 7, 2018”.

**12. Current Ver (Current Version)**

*   Type: Text (string)
*   Description: The version number of the app currently listed on the store.

**13. Android Ver (Android Version)**

*   Type: Text (string)
*   Description: The minimum Android OS version required to run the app (e.g., “4.0.3 and up”).

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for i in dataset.columns.tolist():
  print("No. of unique values in ",i,"is",dataset[i].nunique(),".")

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
# Create a copy of the current dataset and assigning to df
df=dataset.copy()

# We will group by 'Category' and count the occurrences of each 'Type'
pd.DataFrame(df.groupby('Category')['Type'].value_counts().reset_index(name="Count"))

# Define a function that calculates mean and median of numerical columns for a given 'Category'
def get_category_stats(category_code, dataframe):
    # Filter the DataFrame for the given category
    filtered_df = dataframe[dataframe['Category'] == category_code]

    # Select only numeric columns
    numeric_data = filtered_df.select_dtypes(include='number')

    # Calculate mean and median
    mean_values = numeric_data.mean()
    median_values = numeric_data.median()

    return pd.DataFrame({
        'Mean': mean_values,
        'Median': median_values
    })

# Getting Mean Median for 'Rating' Category
game_stats = get_category_stats('GAME', df)
game_stats

# Getting Mean Median for 'Family' Category
family_stats = get_category_stats('FAMILY', df)
family_stats

# Getting Mean Median for 'TOOLS' Category
tools_stats = get_category_stats('TOOLS', df)
tools_stats

# Getting Unique Categories
unique_categories = df['Category'].unique()
print(unique_categories)

# Getting Unique Content Ratings
unique_content_ratings = df['Content Rating'].unique()
print(unique_content_ratings)

# Drop rows with missing app names (essential field)
df.dropna(subset=['App'], inplace=True)

# Clean 'Rating' column: ensure it's numeric and between 1 and 5
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')
df = df[(df['Rating'] >= 1) & (df['Rating'] <= 5)]

# Convert 'Reviews' to numeric
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')
print(df.info())

# Clean 'Size' column
def clean_size(value):
    # Convert the value to string, handle NaN values
    if pd.isna(value):
        return np.nan
    value_str = str(value)

    if value_str == 'Varies with device':
        return np.nan
    if 'M' in value_str:
        return float(value_str.replace('M', '')) * 1024  # Convert MB to KB
    if 'k' in value_str:
        return float(value_str.replace('k', ''))  # Already in KB
    # Handle cases where the value might be a number without 'M' or 'k' or other unexpected formats
    try:
        return float(value_str) # If it's already a number (like a float from previous conversion)
    except ValueError:
        return np.nan # For any other unexpected format

df['Size'] = df['Size'].apply(clean_size)
print(df.info())

# Clean 'Installs' column
df['Installs'] = df['Installs'].str.replace('[+,]', '', regex=True).astype(float)

# Clean 'Price' column
df['Price'] = df['Price'].str.replace('$', '', regex=False).astype(float)

# Fill missing 'Type' with 'Free' (assuming missing implies free)
df['Type'].fillna('Free', inplace=True)

# Fill remaining categorical nulls with mode
for col in ['Content Rating', 'Current Ver', 'Android Ver']:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)

# Convert 'Last Updated' to datetime
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors='coerce')

# Final data info
print(df.info())

#  Distribution of Ratings
plt.figure(figsize=(8, 5))
sns.histplot(df['Rating'], bins=20, kde=True, color='skyblue')
plt.title('Distribution of App Ratings')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

# Most Popular Categories by Number of Apps
category_counts = df['Category'].value_counts().head(10)
category_counts.plot(kind='barh', color='salmon')
plt.title('Top 10 App Categories')
plt.xlabel('Number of Apps')
plt.gca().invert_yaxis()
plt.show()

# Free vs Paid Apps in Each Category
category_type_counts = df.groupby(['Category', 'Type']).size().unstack().fillna(0)
category_type_counts.plot(kind='bar', stacked=True, figsize=(12, 6), colormap='Set2')
plt.title('Free vs Paid Apps per Category')
plt.ylabel('Number of Apps')
plt.xticks(rotation=90)
plt.show()

# Correlation Between Reviews and Rating
sns.scatterplot(data=df, x='Reviews', y='Rating', alpha=0.5)
plt.title('Rating vs. Number of Reviews')
plt.xscale('log')  # Reviews vary widely, log scale improves visibility
plt.xlabel('Number of Reviews (log scale)')
plt.ylabel('Rating')
plt.show()

# Top 10 Most Installed Apps
top_installed = df[['App', 'Installs']].sort_values(by='Installs', ascending=False).drop_duplicates('App').head(10)
top_installed

# Price Distribution of Paid Apps
paid_apps = df[df['Type'] == 'Paid']
plt.figure(figsize=(8, 5))
sns.histplot(paid_apps['Price'], bins=30, color='lightgreen')
plt.xlim(0, 50)  # Exclude extreme outliers for better visualization
plt.title('Price Distribution of Paid Apps')
plt.xlabel('Price ($)')
plt.ylabel('Count')
plt.show()

# Average Rating per Category
avg_rating = df.groupby('Category')['Rating'].mean().sort_values(ascending=False)
avg_rating.plot(kind='bar', figsize=(12, 5), color='orange')
plt.title('Average App Rating by Category')
plt.ylabel('Average Rating')
plt.xticks(rotation=90)
plt.show()

"""### What all manipulations have you done and insights you found?

In this analysis of the Google Play Store dataset, several data wrangling steps were undertaken to clean and prepare the data for meaningful insights. The dataset initially contained issues like missing values, duplicate entries, inconsistent formatting (especially in the "Size", "Installs", and "Price" columns), and improper data types. These were corrected by dropping duplicates, converting columns such as "Reviews", "Price", and "Installs" to numerical values, and transforming "Last Updated" into proper datetime format. The "Size" column was standardized by converting all sizes to kilobytes and handling the "Varies with device" entries. After cleaning the data, various analyses revealed that most apps on the Play Store are free and tend to receive ratings between 4.0 and 4.5, indicating generally positive user feedback. The categories "FAMILY", "GAME", and "TOOLS" have the highest number of apps, while paid apps are much fewer and usually priced under $5. A correlation between the number of reviews and rating was weak, but top-rated apps often had a large number of installs. Categories like "BOOKS_AND_REFERENCE" and "EDUCATION" have some of the highest average ratings, whereas utility apps had comparatively lower user satisfaction. This clean and structured dataset can now be used for further analysis, visualization, or predictive modeling.


**Data Manipulations Performed**


1.   Removed duplicate rows to ensure data uniqueness.
2.   Dropped rows with missing essential values (e.g., app names).
3.   Converted columns --->
  *   Rating → numeric (1 to 5 range)
  *   Reviews, Price, Installs → numeric (cleaned $, +, ,)
  *   Size → standardized in KB (from MB and k)
  *   Last Updated → converted to datetime.
4.   Replaced "Varies with device" and null values appropriately.
5.   Filled missing categorical values (e.g., Type, Content Rating) using mode or assumptions.

*** Insights Derived ***


1.   Most app ratings fall between 4.0 and 4.5, showing general user satisfaction.
2.   Categories like FAMILY, GAME, TOOLS contain the most apps.
3.   Free apps dominate the Play Store; paid apps are rare and usually cheap.
4.   Top apps (e.g., WhatsApp, Facebook) have over 1 billion installs.
5.   Price distribution of paid apps is heavily skewed under $5, with few high-priced outliers.
6.   Weak correlation between number of reviews and rating.
7.   Categories like BOOKS_AND_REFERENCE and EDUCATION have highest average ratings.
8.   Utility apps (like TOOLS and FINANCE) tend to have lower ratings.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1 - Pie Chart on Dependant Variable
"""

# Chart - 1 visualization code
# Calculate the counts for each app type (Free or Paid)
type_counts = df['Type'].value_counts()
# Plotting the pie chart
plt.figure(figsize=(8, 6))
plt.pie(type_counts, labels=type_counts.index, autopct='%1.1f%%', startangle=140, colors=['skyblue', 'lightgreen'])
plt.title('Distribution of App Types (Free vs Paid)')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""##### 1. Why did you pick the specific chart?

The pie chart was chosen to visualize the Type column (Free vs. Paid) because it effectively represents the proportion of categorical data with only a few distinct groups. Since most apps on the Play Store fall into either the Free or Paid category, a pie chart clearly highlights the dominant monetization model. This type of chart provides an immediate and easy-to-understand snapshot of the distribution, making it ideal for presenting high-level insights about how apps are offered to users.

##### 2. What is/are the insight(s) found from the chart?

*   Majority of apps are Free: The chart shows that a very high percentage of apps on the Play Store are free.


*   Paid apps are rare: Only a small fraction of apps require payment, indicating that most developers prefer ad-based or freemium models over upfront payment.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights gained from the pie chart can indeed lead to a positive business impact if used strategically. The observation that the majority of apps on the Play Store are free highlights a key market trend—users generally prefer free apps, and developers are increasingly adopting free models to maximize downloads and user reach. This knowledge can help businesses align their strategies accordingly, such as launching apps with a free version to build a user base before introducing monetization through ads or in-app purchases. It supports user acquisition and market entry, especially for new developers or startups aiming for rapid growth.

However, these insights can also have implications that may lead to negative growth if not approached carefully. The dominance of free apps creates a highly saturated and competitive environment, where standing out becomes challenging without a unique value proposition or marketing strategy. Moreover, relying solely on ads or in-app purchases without ensuring user satisfaction can negatively impact user retention and revenue. Additionally, the abundance of free apps may devalue paid apps in the eyes of users, making it more difficult to monetize high-quality content directly. Therefore, while the insights offer direction, they must be applied thoughtfully to avoid common pitfalls in a competitive app ecosystem.

#### Chart - 2 - Pie chart of app distribution by 'Content Rating'
"""

# Chart - 2 visualization code
# Chart 2: Pie chart of app distribution by 'Content Rating'
content_rating_counts = df['Content Rating'].value_counts()

# Plotting the pie chart
plt.figure(figsize=(8, 6))
plt.pie(content_rating_counts, labels=content_rating_counts.index, autopct='%1.1f%%', startangle=140,
        colors=plt.cm.Paired.colors)
plt.title('Distribution of Apps by Content Rating')
plt.axis('equal')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked the pie chart because it's ideal for showing the proportional distribution of categories—in this case, how apps are divided among different Content Ratings like "Everyone" or "Teen." It quickly communicates which user age group most apps target.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that most apps are rated "Everyone", indicating they are suitable for all age groups. Fewer apps target specific age segments like "Teen" or "Mature 17+", highlighting a broad focus on general audiences.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the insights from the chart can help in a **positive way** for business. Since most apps are rated **"Everyone"**, it shows that making apps for all age groups is a good idea. These apps can reach more people like kids, parents, and students. This can bring more downloads and make the app more popular. Also, it helps the app follow Google Play Store rules easily.

There is no strong sign of **negative growth**, but if companies only focus on "Everyone" apps and ignore groups like **"Teen"** or **"Mature 17+"**, they might **miss a chance** to make something different or new. These smaller groups could also be good markets. So, it’s good to focus on popular areas but also explore less crowded ones for better growth.

#### Chart - 3 - Distribution of Apps by Category (Top 10 categories)
"""

# @title
# Count the top 10 categories
top_categories = df['Category'].value_counts().nlargest(10)

# Plotting the pie chart
plt.figure(figsize=(8, 8))
plt.pie(top_categories, labels=top_categories.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title("Distribution of Apps by Top 10 Categories")
plt.axis('equal')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked the pie chart for showing the top 10 app categories because it’s a simple and clear way to visualize proportions. It helps you quickly see which categories have the most apps and compare their relative sizes. This makes it easy to identify popular segments like "Games", "Tools", or "Education", which can guide business and development decisions.

##### 2. What is/are the insight(s) found from the chart?

The pie chart shows that a few categories, like "Family", "Game", and "Tools", have the largest share of apps on the Play Store. This suggests that developers are highly focused on these areas, possibly due to high user demand. On the other hand, some categories have very few apps, which might indicate less competition and possible opportunities for new apps in those spaces.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the insights from this chart can help create a positive business impact. By identifying which categories have the most apps, businesses can understand where user interest is high and invest in those popular areas like Games or Family apps to attract a large audience. At the same time, noticing less crowded categories can help developers find niche markets with low competition, increasing their chances of standing out and growing.

However, these insights could also hint at potential risks. For example, entering overcrowded categories like "Games" may lead to high competition and lower visibility, especially for new apps without strong marketing. This could slow down growth if the app doesn’t stand out. So, while popular categories offer opportunity, it's important to balance with strategy and uniqueness to avoid negative impact.

#### Chart - 4 - Installs vs Rating
"""

# Chart - 4 visualization code
# Drop rows with missing values in the required columns
install_rating_df = df[['Installs', 'Rating']].dropna()

# Plot Chart 4: Installs vs Rating
plt.figure(figsize=(10, 6))
sns.scatterplot(data=install_rating_df, x='Installs', y='Rating', alpha=0.5)
plt.xscale('log')  # Use log scale for better visibility
plt.title('Chart 4: Installs vs Rating')
plt.xlabel('Installs (log scale)')
plt.ylabel('Rating')
plt.grid(True)
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked the **scatter plot** for Chart 4 (Installs vs Rating) because it’s perfect for showing the **relationship between two numerical variables**. In this case, it helps visualize how the **number of installs** relates to the **user rating**. It allows us to easily spot trends, patterns, or outliers—like whether highly downloaded apps tend to have better ratings or not.

##### 2. What is/are the insight(s) found from the chart?

From the **Installs vs Rating** chart, one key insight is that apps with very high installs usually have **ratings between 4.0 and 4.5**, showing that popular apps tend to maintain good user satisfaction. However, there's no strong upward trend, meaning a high number of installs doesn’t always mean a higher rating. Some apps with low installs also have high ratings, which could signal quality but low visibility.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the insights from the chart can help create a **positive business impact**. Seeing that top-rated apps often have high install numbers shows the importance of **user satisfaction**. Businesses can focus on building high-quality apps that get good reviews to attract more users over time. It also highlights that **ratings influence visibility and trust**, so improving user experience can lead to better growth.

On the other hand, the chart also shows some apps with **many installs but lower ratings**, which could signal **negative user experiences**. If ignored, this can lead to **bad reviews**, lower app store rankings, and eventually **fewer new users**. So, while installs are important, **maintaining quality is key** to avoiding negative growth.

#### Chart - 5 - Reviews vs Rating
"""

# Chart - 5 visualization code
# Drop rows with missing values in Reviews and Rating
review_rating_df = df[['Reviews', 'Rating']].dropna()

# Plot Chart 5: Reviews vs Rating
plt.figure(figsize=(10, 6))
sns.scatterplot(data=review_rating_df, x='Reviews', y='Rating', alpha=0.5)
plt.xscale('log')  # Log scale to handle wide range of reviews
plt.title('Chart 5: Reviews vs Rating')
plt.xlabel('Number of Reviews (log scale)')
plt.ylabel('Rating')
plt.grid(True)
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked the **scatter plot** for Chart 5 (Reviews vs Rating) because it's ideal for showing the **relationship between two continuous variables**. It helps us see how the **number of user reviews** relates to the **app's rating**—whether more reviews usually mean better or worse ratings, and whether highly rated apps get more user feedback. It also helps identify patterns, clusters, or outliers quickly.

##### 2. What is/are the insight(s) found from the chart?

The main insight from the **Reviews vs Rating** chart is that most apps with a **high number of reviews** tend to have **ratings between 4.0 and 4.5**, showing that apps with a lot of user feedback generally maintain good quality. However, there's also a wide spread—some apps with **few reviews** still have high ratings, which suggests they are new but well-liked. Overall, more reviews usually mean higher user trust and app visibility.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can help create a **positive business impact**. They show that getting more **user reviews** while keeping a good **rating** is important for building trust, increasing visibility, and attracting new users. Businesses can focus on encouraging feedback through in-app prompts and improving app quality to maintain high ratings—both of which support growth.

However, if an app collects **many reviews but has a low rating**, it can signal **negative user experience**. This could lead to poor rankings in the app store and a loss of potential users, causing **negative growth**. So while collecting reviews is good, maintaining **quality and user satisfaction** is key to long-term success.

#### Chart - 6 - Top App Categories by Average Rating
"""

# Chart - 5 visualization code
# Calculate average rating per category
avg_rating_by_category = df.groupby('Category')['Rating'].mean().dropna().sort_values(ascending=False).head(15)

# Plotting the bar chart
plt.figure(figsize=(12, 6))
sns.barplot(x=avg_rating_by_category.values, y=avg_rating_by_category.index, palette='coolwarm')
plt.title('Chart 6: Top 15 App Categories by Average Rating')
plt.xlabel('Average Rating')
plt.ylabel('App Category')
plt.xlim(0, 5)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked the **bar chart** for Chart 6 (Average Rating by App Category) because it's the best way to **compare average values** across multiple categories. It clearly shows which app categories have the **highest user satisfaction**, based on average ratings. The horizontal bars make it easy to read and compare across categories like **Education**, **Health**, or **Productivity**, helping businesses identify strong-performing areas.

##### 2. What is/are the insight(s) found from the chart?

The insight from this chart is that some categories, like Education, Health & Fitness, and Books & Reference, often have the highest average ratings, showing that users are very satisfied with apps in these areas. This suggests these categories are trusted and valued by users. On the other hand, some categories may have lower average ratings, hinting at possible quality issues or user dissatisfaction in those segments.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can help create a **positive business impact**. By identifying categories with the **highest average ratings**, businesses can focus on developing apps in areas where users are generally more satisfied, such as **Education** or **Health & Fitness**. High user satisfaction leads to better reviews, stronger app store rankings, and more organic downloads—all of which support business growth.

On the other hand, categories with **low average ratings** may point to **user dissatisfaction**, which can lead to **negative growth** if issues aren't addressed. Apps in these areas might struggle with retention, poor visibility, or low user trust. Ignoring these signals could result in lost users and missed opportunities for improvement.

#### Chart - 7- Average Price by App Category (Paid Apps Only)
"""

# Chart - 7 visualization code
# Filter paid apps
paid_apps = df[df['Type'] == 'Paid']

# Calculate average price by category
avg_price_by_category = paid_apps.groupby('Category')['Price'].mean().dropna().sort_values(ascending=False).head(15)

# Plotting the bar chart
plt.figure(figsize=(12, 6))
sns.barplot(x=avg_price_by_category.values, y=avg_price_by_category.index, palette='viridis')
plt.title('Chart 7: Top 15 App Categories by Average Price (Paid Apps)')
plt.xlabel('Average Price ($)')
plt.ylabel('App Category')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked the **bar chart** for Chart 7 (Average Price by App Category) because it's ideal for comparing **monetary values** across multiple categories. It clearly shows which app categories tend to have **higher average prices** among paid apps. This helps identify which segments are considered more valuable by developers and where users are willing to spend more money.

##### 2. What is/are the insight(s) found from the chart?

The insight from this chart is that certain categories—like **Medical**, **Business**, or **Education**—often have **higher average prices** for paid apps. This suggests that users in these segments are more likely to pay for specialized or professional content. It also indicates that developers see more **monetization potential** in these categories compared to others like **Games** or **Lifestyle**, which tend to have lower prices or rely more on free models.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can help create a **positive business impact**. Knowing which categories have **higher average prices** allows businesses to focus on segments where users are **willing to pay more**, like **Medical** or **Business** apps. This supports better revenue planning and product positioning for premium offerings.

However, there’s also a risk of **negative growth** if prices are set too high in categories where users expect free or low-cost apps (like **Games** or **Entertainment**). Overpricing in such categories may lead to **fewer downloads**, **low engagement**, and **negative reviews**, which can harm visibility and reputation. So, price strategy must align with user expectations to avoid growth barriers.

### Chart - 8 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
# Create a correlation heatmap using numerical features

# Selecting only numeric columns
numeric_df = df.select_dtypes(include=['float64', 'int64'])

# Calculating correlation matrix
correlation_matrix = numeric_df.corr()

# Plotting the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Heatmap of Numeric Features')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked the **correlation heatmap** because it's the best way to visualize **how strongly numerical variables are related** to each other in one view. It helps identify patterns—like whether **apps with more installs tend to get more reviews** or whether **higher prices affect ratings**. The color-coded layout makes it easy to spot both **strong and weak relationships** quickly, which is useful for deeper analysis and decision-making.

##### 2. What is/are the insight(s) found from the chart?

From the correlation heatmap, a typical insight is that there's a **strong positive correlation between Installs and Reviews**, meaning apps that are downloaded more also tend to receive more reviews. This suggests that user engagement increases with app popularity. However, **Rating** usually shows **weak or no strong correlation** with other variables like Price or Installs, indicating that **user satisfaction is not always tied to how much an app costs or how many times it’s downloaded**.

### Chart - 9 - Pair Plot
"""

# Generate a pair plot for selected numeric features

# Select a smaller sample and fewer variables for clarity and performance
sample_df = df[['Rating', 'Reviews', 'Installs', 'Price']].dropna().sample(500, random_state=42)

# Plotting the pair plot
sns.pairplot(sample_df, diag_kind='kde', corner=True)
plt.suptitle('Pair Plot of Selected Numeric Features', y=1.02)
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked the **pair plot** because it allows you to **visually compare multiple relationships at once** between several numeric variables. It shows **scatter plots for each pair** and **distributions on the diagonal**, helping to quickly spot **correlations**, **clusters**, or **outliers**. It’s especially useful for exploring how variables like **Rating**, **Installs**, **Reviews**, and **Price** interact with each other in a single view.

##### 2. What is/are the insight(s) found from the chart?

The pair plot provides a visual summary of how key numeric features—such as Rating, Reviews, Installs, and Price—are related to each other. One clear insight is the strong positive relationship between Installs and Reviews, suggesting that as more users download an app, the number of reviews also increases. This indicates higher engagement with popular apps. However, Ratings show little to no strong correlation with other variables, meaning that user satisfaction (reflected in ratings) is not directly tied to how many people install or review an app, or even its price. Additionally, the distribution of Price is highly skewed, with most apps being either free or low-cost, while a small number are priced significantly higher. The plot also helps highlight outliers—such as apps with extremely high installs or unusually high prices—which can guide further investigation.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

To help the client achieve their **business objective**—such as increasing app downloads, user satisfaction, and revenue—here are key suggestions based on the analysis:

The client should focus on **improving app quality**, as apps with higher ratings tend to attract and retain more users. This includes optimizing user experience, fixing bugs quickly, and responding to user feedback. Since categories like **Education**, **Health**, and **Books** consistently receive high ratings, the client may consider developing or marketing apps in these areas to target highly satisfied user segments.

Encouraging more **user reviews** can also boost visibility in app stores. This can be done through in-app prompts or incentives, but only after ensuring a positive user experience to avoid negative feedback. Additionally, the pricing strategy should align with category norms—premium pricing may work well for niches like **Medical** or **Business**, but not for general categories like **Games** where free models are expected.

Finally, monitoring **key performance indicators (KPIs)** like installs, ratings, and reviews over time—and responding with data-driven decisions—will ensure the app remains competitive and aligned with user needs. This strategy supports sustainable growth and positive brand perception.

# **Conclusion**

The analysis of Play Store app data reveals valuable insights into what drives app success. Key findings show that **higher installs are strongly linked to more user reviews**, while **ratings reflect user satisfaction independently of popularity or price**. Categories like **Education**, **Health & Fitness**, and **Books & Reference** tend to receive better ratings, indicating strong user trust and satisfaction in these areas.

Apps with many installs but low ratings suggest the need for **quality improvement**, while categories with high prices—such as Medical or Business—indicate where users are willing to pay more for specialized content.

Overall, businesses should focus on delivering quality experiences, encouraging genuine user reviews, and pricing apps according to user expectations in each category. By aligning product decisions with these insights, companies can boost user engagement, build loyalty, and achieve long-term growth in the competitive app market.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""